### PR TITLE
make toml work with parslet >= 1.7

### LINKED ISSUE #43: Fails to build against parslet 1.7.1
Hi!

Can you probably make a sense out of the following build error?

NoMethodError: undefined method `map' for "strings"@50:Parslet::Slice

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818155

Thank you and Greetings
Peter

### PR DESCRIPTION
**Pull request by boutil**
This change makes toml work with newer parslet. As the order of insertion of rules have changed in parslet to give newer rules higher priority, rules have been exchanged in transform.rb.

This closes #43.

### CODE REVIEW

**Comment by jm** [comment]
Hm something is weird with CI on this for some reason.  I'll look into it, and if I can figure it out, I'll merge it (heck, from the looks of it, it's unrelated so I'll merge it anyhow but I'd like to get it figure it beforehand if possible...).

**Comment by aaronlippold** [comment]
Hi, any progress on this, this is causing an issue with some of my work with InSpec and Parslet ( which is now up to v1.8 ) so would love to see this integrated. Thanks.

**Comment by jm** [comment]
Just merged another branch that fixed it for newer Parslet versions!  So very sorry I let this branch decay, but fortunately someone else PR'd another up to date one recently.  😄
